# 1. Write Python code for addition, subtraction, multiplication, element-wise multiplication, determinant, the inverse of the matrix using NumPy and SciPy package.

In [6]:
import numpy as np
from scipy import linalg

# Create two sample matrices
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# 1. Matrix Addition
print("Matrix Addition:")
C = A + B  # or np.add(A, B)
print(C)

# 2. Matrix Subtraction
print("\nMatrix Subtraction:")
D = A - B  # or np.subtract(A, B)
print(D)

# 3. Matrix Multiplication (dot product)
print("\nMatrix Multiplication:")
E = np.dot(A, B)  # or A @ B in Python 3.5+
print(E)

# 4. Element-wise Multiplication (Hadamard product)
print("\nElement-wise Multiplication:")
F = A * B  # or np.multiply(A, B)
print(F)

# 5. Matrix Determinant
print("\nDeterminant of A:")
det_A = np.linalg.det(A)
print(det_A)

# 6. Matrix Inverse
print("\nInverse of A:")
inv_A = np.linalg.inv(A)  # or linalg.inv(A) from SciPy
print(inv_A)

# Verification: A * inv(A) should be identity matrix
print("\nVerification (A * inv(A)):")
print(np.dot(A, inv_A))

Matrix Addition:
[[ 6  8]
 [10 12]]

Matrix Subtraction:
[[-4 -4]
 [-4 -4]]

Matrix Multiplication:
[[19 22]
 [43 50]]

Element-wise Multiplication:
[[ 5 12]
 [21 32]]

Determinant of A:
-2.0000000000000004

Inverse of A:
[[-2.   1. ]
 [ 1.5 -0.5]]

Verification (A * inv(A)):
[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


# 2. Write Python code to calculate eigenvalue and eigenvector of a matrix. Check the orthogonality of the eigenvector.

In [7]:
import numpy as np
from numpy.linalg import eig, norm

# Create a sample symmetric matrix (for real eigenvalues)
A = np.array([[4, 1, -1],
              [1, 2, 1],
              [-1, 1, 3]])

# 1. Calculate eigenvalues and eigenvectors
eigenvalues, eigenvectors = eig(A)

print("Eigenvalues:")
print(eigenvalues)

print("\nEigenvectors (columns):")
print(eigenvectors)

# 2. Check orthogonality of eigenvectors
# For symmetric matrices, eigenvectors should be orthogonal
n = eigenvectors.shape[1]  # Number of eigenvectors

print("\nOrthogonality Check (dot products between eigenvectors):")
for i in range(n):
    for j in range(i+1, n):
        dot_product = np.dot(eigenvectors[:, i], eigenvectors[:, j])
        print(f"v{i+1} • v{j+1} = {dot_product:.5f}")

# 3. Normalize eigenvectors and verify orthonormality
print("\nNormalized eigenvectors and orthonormality check:")
normalized_eigenvectors = eigenvectors / norm(eigenvectors, axis=0)

for i in range(n):
    for j in range(n):
        dot_product = np.dot(normalized_eigenvectors[:, i], 
                            normalized_eigenvectors[:, j])
        print(f"v{i+1} • v{j+1} = {dot_product:.5f}", end=" | ")
    print()

# 4. Verification: A * v = λ * v
print("\nVerification of eigenvalue-eigenvector pairs:")
for i in range(n):
    λ = eigenvalues[i]
    v = eigenvectors[:, i]
    Av = np.dot(A, v)
    λv = λ * v
    print(f"For eigenvalue {λ:.3f}:")
    print("A*v:", Av)
    print("λ*v:", λv)
    print("Difference:", norm(Av - λv), "\n")

Eigenvalues:
[0.78568026 4.67513087 3.53918887]

Eigenvectors (columns):
[[-0.39711255  0.88765034  0.23319198]
 [ 0.75578934  0.17214786  0.63178128]
 [-0.52065737 -0.42713229  0.73923874]]

Orthogonality Check (dot products between eigenvectors):
v1 • v2 = -0.00000
v1 • v3 = -0.00000
v2 • v3 = 0.00000

Normalized eigenvectors and orthonormality check:
v1 • v1 = 1.00000 | v1 • v2 = -0.00000 | v1 • v3 = -0.00000 | 
v2 • v1 = -0.00000 | v2 • v2 = 1.00000 | v2 • v3 = 0.00000 | 
v3 • v1 = -0.00000 | v3 • v2 = 0.00000 | v3 • v3 = 1.00000 | 

Verification of eigenvalue-eigenvector pairs:
For eigenvalue 0.786:
A*v: [-0.31200349  0.59380876 -0.40907021]
λ*v: [-0.31200349  0.59380876 -0.40907021]
Difference: 9.50197851991224e-16 

For eigenvalue 4.675:
A*v: [ 4.1498815   0.80481377 -1.99689934]
λ*v: [ 4.1498815   0.80481377 -1.99689934]
Difference: 3.722145839155691e-15 

For eigenvalue 3.539:
A*v: [0.82531046 2.23599328 2.61630552]
λ*v: [0.82531046 2.23599328 2.61630552]
Difference: 7.1088959

# 3. Calculate span and basis of a vector space using Python.

In [8]:
import numpy as np
from numpy.linalg import matrix_rank, qr

def find_basis(vectors):
    """
    Find a basis for the space spanned by the given vectors.
    
    Parameters:
    vectors - list of vectors or 2D numpy array (each column is a vector)
    
    Returns:
    basis - matrix where columns form a basis for the space
    """
    # Convert to numpy array if not already
    vectors = np.array(vectors)
    
    # If vectors are given as rows, transpose to make them columns
    if vectors.shape[0] < vectors.shape[1]:
        vectors = vectors.T
    
    # Perform QR decomposition
    Q, R = qr(vectors)
    
    # The rank reveals the number of basis vectors
    rank = matrix_rank(vectors)
    
    # The first 'rank' columns of Q form an orthonormal basis
    basis = Q[:, :rank]
    
    return basis

# Example 1: Linearly independent vectors
v1 = np.array([1, 0, 0])
v2 = np.array([0, 1, 0])
vectors1 = np.column_stack((v1, v2))

print("Example 1 - Linearly independent vectors:")
print("Original vectors:")
print(vectors1)

basis1 = find_basis(vectors1)
print("\nBasis for the space:")
print(basis1)
print("Dimension of space:", basis1.shape[1])

# Example 2: Linearly dependent vectors
v3 = np.array([1, 2, 3])
v4 = np.array([2, 4, 6])  # v4 = 2*v3
v5 = np.array([1, 0, 1])
vectors2 = np.column_stack((v3, v4, v5))

print("\nExample 2 - Linearly dependent vectors:")
print("Original vectors:")
print(vectors2)

basis2 = find_basis(vectors2)
print("\nBasis for the space:")
print(basis2)
print("Dimension of space:", basis2.shape[1])

# Example 3: Spanning R^3
v6 = np.array([1, 0, 0])
v7 = np.array([1, 1, 0])
v8 = np.array([1, 1, 1])
vectors3 = np.column_stack((v6, v7, v8))

print("\nExample 3 - Spanning R^3:")
print("Original vectors:")
print(vectors3)

basis3 = find_basis(vectors3)
print("\nBasis for the space:")
print(basis3)
print("Dimension of space:", basis3.shape[1])

Example 1 - Linearly independent vectors:
Original vectors:
[[1 0]
 [0 1]
 [0 0]]

Basis for the space:
[[ 1.  0.]
 [-0.  1.]
 [-0. -0.]]
Dimension of space: 2

Example 2 - Linearly dependent vectors:
Original vectors:
[[1 2 1]
 [2 4 0]
 [3 6 1]]

Basis for the space:
[[-0.26726124  0.95618289]
 [-0.53452248 -0.04390192]
 [-0.80178373 -0.28945968]]
Dimension of space: 2

Example 3 - Spanning R^3:
Original vectors:
[[1 1 1]
 [0 1 1]
 [0 0 1]]

Basis for the space:
[[ 1.  0.  0.]
 [-0.  1.  0.]
 [-0. -0.  1.]]
Dimension of space: 3
